# Problem Market Fit:
"""
The "Bhaktapur Backdrop" Concept Generator 🎬

    Agent 1 (Trend Spotter): Takes a basic clothing item she wants to sell (e.g., "Pastel Kurti set" or "Casual summer dress") and pairs it with a trending TikTok audio style or challenge concept.

    Agent 2 (Local Scriptwriter): Formats a precise JSON payload detailing the exact visual shot list (e.g., Shot 1: Walking past the standard wood-carved windows in Sakotha), the on-screen text overlays, and the Romanized Nepali voiceover script.
"""
import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

#Agents Schema
class Agent:
    role:str
    content:str

    def __init__(self, role,content):
        self.role = role
        self.content = content

# Agent 1 (Trend Spotter) 📊: Takes the clothing item input and outputs a creative TikTok concept paired with a local vibe.
trend_spotter_prompt = """
Persona: You are a TikTok Fashion Trend Spotter specializing in the Nepali retail market.
Task: Analyze the provided clothing image and description. Brainstorm a high-converting TikTok video concept.
Instructions:
1. Connect the clothing style/color to a visually appealing setting or cultural element around Sakotha or Bhaktapur.
2. Ensure the concept targets both local foot traffic (visiting the store) and online orders (DM to buy).
3. Output a creative video hook and a general angle for the video.
"""
trend_spotter = Agent(role="system", content=trend_spotter_prompt)

# Agent 2 (Local Scriptwriter) ✍️: Takes Agent 1's concept and transforms it into a structured JSON script featuring Sakotha backdrops and Romanized Nepali lines.
local_scriptwriter_prompt = """
You are a Local Scriptwriter. Your task is to take the concept generated by the Trend Spotter and transform it into a structured JSON script. The script should include the following elements:
1. Visual shot list with descriptions
2. On-screen text overlays
3. Nepali voiceover script
"""
local_scriptwriter = Agent(role="system", content=local_scriptwriter_prompt)

def run():
    chat_completions = client.chat.completions.create(
        messages=[
            {
                "role":"system",
                "content":trend_spotter.content

            },
            {
                "role":"user",
                "content": local_scriptwriter.content,
            }
        ],
        model="llama-3.2.-11b-vision-preview",
    )
    print(chat_completions.choices[0].message.content)

run()